DutchTreat/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using DutchTreat.Data;
using DutchTreat.Data.Entities;
using DutchTreat.Models;
using DutchTreat.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.WebEncoders.Testing;

namespace DutchTreat.Controllers
{
    public class AppController : Controller
    {
        private readonly IMailService _mailService;
        private readonly IDutchTreatRepository _dutchTreatRepository;
        
        public AppController(IMailService mailService, IDutchTreatRepository dutchTreatRepository)
        {
            _mailService = mailService;
            _dutchTreatRepository = dutchTreatRepository;
        }
        
        public IActionResult Index()
        {
            IEnumerable<Product> products = _dutchTreatRepository.GetAllProducts();
            return View();
        }

        [HttpGet("contact")]
        public IActionResult Contact()
        {
            // throw new InvalidOperationException("I will not work");
            return View();
        }
        
        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            Console.WriteLine("I am here1"+model.ToString());
            if (ModelState.IsValid)
            {
                // Sent the email
                _mailService.SendMessage(model.Email, "Query Acknowledged", "Will reach you back in 2 business days");
                ViewBag.UserMessage = "Mail Sent";
                ModelState.Clear();
            }
            // throw new InvalidOperationException("I will not work");
            return View();
        }
        
        public IActionResult About()
        {
            ViewBag.Title = "About";
            return View();
        }
        
        public IActionResult Shop()
        {
            //Before angular
            // IEnumerable<Product> products = _dutchTreatRepository.GetAllProducts();
            // return View(products);
            // After angular
            return View();
        }
    }
}

DutchTreat/Controllers/Drums/DrumsReportsController.cs
using Microsoft.AspNetCore.Mvc;

namespace DutchTreat.Controllers.Drums
{
    public class DrumsReportsController: Controller
    {
        public IActionResult CreateReportCard()
        {
            ViewBag.Title = "Create Report Card Controller";
            return View();
        }
    }
}

DutchTreat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Dutch Treat: @ViewBag.Title</title>
        <environment names="Development">
            <link rel="stylesheet" href="~/node_modules/bootstrap/dist/css/bootstrap.css"/>
            <link rel="stylesheet" href="~/node_modules/font-awesome/css/font-awesome.css"/>
            <link rel="stylesheet" href="~/css/style.css">    
        </environment>
        <environment names="Staging,Production">
            <link rel="stylesheet" href="~/node_modules/bootstrap/dist/css/bootstrap.min.css"/>
            <link rel="stylesheet" href="~/node_modules/font-awesome/css/font-awesome.min.css"/>
            <link rel="stylesheet" href="~/css/style.css">
        </environment>
        
    </head>
    <body>
        <header class="container">
                <nav class="navbar navbar-dark bg-dark navbar-expand-md">
                    <h1 class="navbar-brand"> <i class="fa fa-paint-brush"></i>Welcome to Dutch Treat</h1> 
                <button class="navbar-toggler" data-toggle="collapse" data-target="#navMenu1">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div id="navMenu1" class="navbar-collapse collapse">
                    <ul class="navbar-nav">
                        @* <li class="nav-item"> *@
                        @*     <a class="nav-link" asp-controller="DrumsReports" asp-action="CreateReportCard">Drums</a> *@
                        @* </li> *@
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="App" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="App" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="App" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="App" asp-action="Shop">Angular</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                       
                    </ul>
                </div>
            </nav>
        </header>
        <section class="container">
            <h1 class="text-center">@ViewBag.Title</h1>
            @RenderBody()
        </section>
    <footer class="container">
        <div class="text-center">Copyright 2020 Dutch Treat LLC</div>
    </footer>
    <environment names="Development">
        <script src="~/node_modules/jquery/dist/jquery.js"></script>
        <script src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/js/index.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="//ajax.aspnetcdn.com/ajax/jquery/jquery-3.5.0.min.js"
                asp-fallback-src="~/node_modules/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="//ajax.aspnetcdn.com/ajax/bootstrap/4.4.1/bootstrap.bundle.min.js"
                asp-fallback-src="~/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/dist/dutchtreat.min.js" asp-append-version="true"></script>
    </environment>
        @RenderSection("scripts", false)
    </body>
</html>